### ISSUE TITLE
Upstream DNSLIB problems

### ISSUE THREAD

**Issue by PeeHaa** [ekinhbayar/gitamp#26]
Just putting it here in case somebody ever hits something related:

> notice Undefined offset: 0 in /opt/gitamp/vendor/amphp/socket/lib/functions.php on line 90

No idea what's going on. Maybe it was a glitch / connection hickup, but I doubt it should throw notices in our face.

It started working again after restart. We need to keep an eye on it to see if it goes funky again.

**Comment by PeeHaa** [comment]
Captain's log: today it blew up again.

**Comment by ekinhbayar** [comment]
Aaand it blew up again. The log is full of [these](https://gist.github.com/ekinhbayar/0057d477aacc9dfdc18a4ef5eb573260).

**Comment by PeeHaa** [comment]
No idea what this means, but:

http://chat.stackoverflow.com/rooms/11/conversation/dnslib-fuckery

**Comment by PeeHaa** [comment]
Just got this on my windows box.

Once DNS fails it just keeps failing even after fixing the connection.

> [2017-01-29 15:33:45] notice fwrite(): send of 32 bytes failed with errno=10022 Er is een ongeldig argument opgegeven.
 in D:\Web\gitamp\vendor\amphp\dns\lib\DefaultResolver.php on line 198
[2017-01-29 15:33:48] warning unpack(): Type n: not enough input, need 2, have 1 in D:\Web\gitamp\vendor\amphp\dns\lib\DefaultResolver.php on line 556

**Comment by kelunik** [comment]
Every notice should be reported upstream.

**Comment by kelunik** [comment]
This should actually never happen, because either at least one record should be returned or an exception be thrown.

**Comment by kelunik** [comment]
I think this can be closed, as it's using the Amp v2 version of `amphp/dns` now?

**Comment by PeeHaa** [comment]
yes. Thought the same. <3
