### ISSUE TITLE
Add tooling to force and check for fqn function calls

### ISSUE THREAD

**Issue by PeeHaa** [ekinhbayar/gitamp#41]
We need to introduce some tooling to force / check for fq function calls in the project.

We already have been looking at pre-commit hooks to check for and fix this using https://github.com/nilportugues/php-backslasher. But commit hooks are either only locally and cannot be added to the repo or involve git fuckery with custom hooks directories.

We also tried some way of CI integration, but without much success.

If somebody has some good ideas about this suggestions are very welcome. 

The latest version of phpstorm support inspections for this so at the very least we should setup and add the IDEA config to the project which includes this inspection if possible.

**Comment by PeeHaa** [comment]
We have a script running that checks and fails the build when there are missing fqn.

Will see how this works out / how workable this is.

**Comment by kelunik** [comment]
See #43.
