### ISSUE TITLE
v2_rewrite

### ISSUE THREAD

**Issue by ekinhbayar** [ekinhbayar/gitamp#45]
May I keep this issue open for issues and questions that come up when debugging/rewriting gitamp for amp v2 @kelunik, @trowski, everyone?

To start with, [here](https://gist.githubusercontent.com/ekinhbayar/2e54accaf3bfc5e6f030c7b57dd636a7/raw/d5650f7ffb2c98d752e19e8877e343e809641313/gitamp.log) is what I look at when I try to run it on v2_rewrite branch. 

If I try to get the previous exception in BasicClient, 
`var_dump($dnsException->getPrevious()->getMessage());`
It shows me `string(27) "Multiple errors encountered"`, which is also on above gist. Btw, getReasons() is undefined, @kelunik. Am I doing something wrong here?

**Comment by kelunik** [comment]
@ekinhbayar Probably, yes, see https://github.com/amphp/amp/blob/bb1db1609fb1a07bbb621e944dd4c170af3319e7/lib/MultiReasonException.php#L22-L24.

**Comment by ekinhbayar** [comment]
If I catch the MultiReasonException and call for getReasons() I end up with https://gist.githubusercontent.com/ekinhbayar/1d46ae3c88701a4fe9c969cccd6b2680/raw/25d6bd2495cca18067fad75cc8b10df4716e4556/reasons.log ... @kelunik. Also I found out, if I disable opCache and rerun it again, I get 
> **[2017-06-30 20:13:03]** gitamp.ERROR: Failed to send GET request to API endpoint {"exception":"[object] (Amp\\Artax\\DnsException(code: 0): Resolving the specified domain failed: 'api.github.com:443' at /home/ekinhb/PhpstormProjects/gitampLatest/vendor/amphp/artax/lib/BasicClient.php:351, Amp\\Dns\\NoRecordException(code: 0): No records returned for api.github.com at /home/ekinhb/PhpstormProjects/gitampLatest/vendor/amphp/dns/lib/BasicResolver.php:247)"} []
**[2017-06-30 20:13:03]** critical Amp\Dns\NoRecordException: No records returned for api.github.com in /home/ekinhb/PhpstormProjects/gitampLatest/vendor/amphp/dns/lib/BasicResolver.php:247


first.

**Comment by kelunik** [comment]
I really don't get why it's failing with

```
string(235) "Argument 1 passed to Amp\Dns\BasicResolver::assertAcceptableResponse() must be an instance of LibDNS\Messages\Message, array given, called in /home/ekinhb/PhpstormProjects/gitampLatest/vendor/amphp/dns/lib/BasicResolver.php on line 212"
```

As far as I can see from the trace, it's a `Message` object and no array. Could you try dumping the result inside `BasicResolver`?

**Comment by ekinhbayar** [comment]
This gist have both cases, with and without OPcache enabled [here](https://gist.github.com/ekinhbayar/d05ff4bf2dc38bf633e22ceecba809d5)

**Comment by kelunik** [comment]
There's definitely a bug in OPCache.

**Comment by ekinhbayar** [comment]
Yes, that's what I believe as well.

**Comment by kelunik** [comment]
See amphp/dns#58.

**Comment by ekinhbayar** [comment]
BTW, [these](https://gist.github.com/ekinhbayar/709584accaff2de67f80d49fa8ed93c6) are what I see when I run amphp/dns tests on my end @kelunik.

**Comment by kelunik** [comment]
Yes, looks pretty much like that here, too. Works fine without OPCache.

**Comment by ekinhbayar** [comment]
Looking at [this](https://gist.github.com/ekinhbayar/709584accaff2de67f80d49fa8ed93c6#file-dnswithoutopcache-log) bit made me worried about my own dev environment as I still have `Errors: 9, Failures: 1`.
