### ISSUE TITLE
Setup CI and tests

### ISSUE THREAD

**Issue by PeeHaa** [ekinhbayar/gitamp#6]
- [x] write all missing tests
- [x] set up travis
- [x] set up scrutinizer
- [x] add commit bot?
- [ ] add CS checker on travis builds?
- [x] add badges to the readme

**Comment by PeeHaa** [comment]
@ekinhbayar could you add the repo to scrutinizer and travis in preparation of above please?

**Comment by ekinhbayar** [comment]
Done. Also made a head start for missing tests on unit-tests branch but still unsure about the Storage one I have there.

**Comment by ekinhbayar** [comment]
[Scrutinizer](https://scrutinizer-ci.com/g/ekinhbayar/gitamp/?branch=master) has a CS checker in place. I think I haven't added CS checks to Travis CI anywhere yet. 

Also I added the mention-bot webhook in repo settings, not sure if I need to anything else than that, it's only watching new PR's.

**Comment by PeeHaa** [comment]
All tests are written. Pretty sure the `RedisCounter` is also covered.

I have opened an issue on the code-coverage repo https://github.com/sebastianbergmann/php-code-coverage/issues/501

**Comment by PeeHaa** [comment]
It looks like there is/was an issue with function imports. Using fqn fixed the code coverage https://github.com/ekinhbayar/gitamp/commit/174b22b8de0fdfe28638aef9edbef70ccb1f193b.

It looks like the latest code-coverage release will fix the issue, but it's changelog is... uhhhmm.. not helpful at all.

**Comment by PeeHaa** [comment]
Updating the dependencies indeed fixed the coverage issue we were seeing. So this is fixed in https://github.com/ekinhbayar/gitamp/commit/9e7d3efc17ab232383ff0253514c9c566a07115c

**Comment by PeeHaa** [comment]
Closing this issue for now, because I am annoyed by the issue hanging on a single thing.

If we want to try to add the cs fixer in the future again just open a new issue for it.
